# Generated by Django 6.0.4 on 2026-04-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caldy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("raw_value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("float", "Float"),
                            ("json", "JSON"),
                        ],
                        default="str",
                        max_length=10,
                    ),
                ),
                ("group", models.CharField(blank=True, db_index=True, max_length=100)),
                ("is_secret", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "configs",
                "ordering": ["group", "key"],
            },
        ),
    ]
