# Generated by Django 6.0.4 on 2026-04-27 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caldy", "0002_organization_organizationmembership_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("handle", models.SlugField(max_length=128, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("location", models.CharField(blank=True, max_length=256, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                (
                    "owner_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_accounts",
                        to="caldy.organization",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("owner_org__isnull", True),
                                ("owner_user__isnull", False),
                            ),
                            models.Q(
                                ("owner_org__isnull", False),
                                ("owner_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="account_owner_exactly_one",
                    )
                ],
            },
        ),
    ]
