# Generated by Django 6.0.4 on 2026-04-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caldy", "0004_event_eventinstance_schedule_event_schedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("guest_name", models.CharField(max_length=256)),
                ("guest_email", models.EmailField(max_length=254)),
                ("guest_phone", models.CharField(blank=True, max_length=32, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="caldy.eventinstance",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-booked_at"],
            },
        ),
    ]
