# Generated by Django 6.0.4 on 2026-04-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caldy", "0005_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reference",
            field=models.CharField(
                blank=True, editable=False, max_length=8, unique=True
            ),
        ),
    ]
